export const themes = {
  light: {
    background: "#FFFFFF",
    text: "#232323",
    primary: "#6200EE",
    secondary: "#0000",
    border: "#c0c0c0",
    faintText: "#aaaa",
    buttonText: "#fff",
    buttonBg: "#000",
    black: "#000",
    surfaceVariant: "#cc0000",
  },
  dark: {
    background: "#121212",
    text: "#FFFFFF",
    primary: "#6200EE",
    secondary: "#03DAC6",
    border: "#aaaaaa",
    faintText: "#aaaaaa",
    buttonText: "#000",
    buttonBg: "#fff",
    black: "#000",
    surfaceVariant: "#cc0000",
  },
};
